core/urls.py
import os

from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import TemplateView

from . import settings
from . import views


urlpatterns = [
    path('accounts/signup/', views.UserCreationView.as_view(), name = 'signup'),
    path('accounts/profile/', views.UserProfileView.as_view(), name = 'profile'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('robots.txt', TemplateView.as_view(template_name = 'core/robots.txt')),
    path('', include('fantasy.urls')),
    path('', lambda req: None, name = 'index'),  # type: ignore # Root URL alias, handled by app
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        'favicon.ico',
        document_root = os.path.join(settings.BASE_DIR, 'core', 'static', 'favicon.ico'),
    )

fantasy/urls.py
from django.urls import path, include

from .constants import Genders
from . import views


app_name = 'fantasy'

leaderboard_subpatterns = [
    path(
        'men/',
        views.LeaderboardView.as_view(),
        {'gender': Genders.MEN},
        name = 'leaderboard_men',
    ),
    path(
        'women/',
        views.LeaderboardView.as_view(),
        {'gender': Genders.WOMEN},
        name = 'leaderboard_women',
    ),
    path(
        '',
        views.LeaderboardView.as_view(),
        name = 'leaderboard',
    ),
]

urlpatterns = [
    path('events/', views.EventsList.as_view(), name = 'events'),
    path('guide-rules/', views.RulesView.as_view(), name = 'rules'),
    path(
        'privacy/',
        views.RulesView.as_view(template_name = 'fantasy/privacy.html'),
        name = 'privacy',
    ),
    path('buy/', views.buy, name = 'buy'),
    path('sell/', views.sell, name = 'sell'),
    path('switch/<int:purchase_id>/', views.Switch.as_view(), name = 'switch'),
    path('market-hold/', views.market_hold, name = 'market-hold'),
    path('<slug:event_tag>/', include([
        path('men/', views.MarketView.as_view(), {'gender': Genders.MEN}, name = 'men'),
        path('women/', views.MarketView.as_view(), {'gender': Genders.WOMEN}, name = 'women'),
        path('leaderboard/', include(leaderboard_subpatterns)),
        path('teams/<team_name>/', views.TeamView.as_view(), name = 'team'),
        path(
            'guide-rules/',
            views.EventBase.as_view(template_name = 'fantasy/rules.html'),
            name = 'rules',
        ),
        path(
            'privacy/',
            views.EventBase.as_view(template_name = 'fantasy/privacy.html'),
            name = 'privacy',
        ),
        path('', views.EventView.as_view(), name = 'event'),
    ])),
    path('', views.IndexView.as_view(), name = 'index'),
]

fantasy/views.py
from typing import TypedDict, Iterable, Any, TYPE_CHECKING

from django.views.generic.detail import DetailView
from django.views.generic.base import ContextMixin, TemplateView
from django.views.decorators.http import require_POST
from django.utils.decorators import method_decorator
from django.utils.datastructures import MultiValueDictKeyError
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from django.db import models as db
from django.contrib.auth import models as auth
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages
from django.shortcuts import redirect, get_object_or_404
from django.http import HttpRequest, HttpResponse, HttpResponseBase

from .constants import Genders, GENDERS_OVERALL, money, timings
from . import models
from . import utils
from . import transactions
from . import errors


ContextKwargs = dict[str, Any]
ContextDict = dict[str, Any]


class EventAugmentation(TypedDict):
    user_fantasy: models.GameEntry
    _user_fantasy: list[models.GameEntry]

    mens_crew_ready: bool
    womens_crew_ready: bool


class CrewPopularity(TypedDict):
    purchase_count: int
    popularity: float


if TYPE_CHECKING:
    from django_stubs_ext import WithAnnotations

    EventDetailView = DetailView[models.Event]
    AugmentedEvent = WithAnnotations[models.Event, EventAugmentation]

    CrewWithPopularity = WithAnnotations[models.Crew, CrewPopularity]
    PositionWithPopularity = WithAnnotations[models.Position, CrewPopularity]

else:
    EventDetailView = DetailView

    CrewWithPopularity = models.Crew
    PositionWithPopularity = models.Position



class FantasyBaseMixin(ContextMixin):

    def get_context_data(self, **kwargs: ContextKwargs) -> ContextDict:
        context = super().get_context_data(**kwargs)
        context['money'] = money
        context['timings'] = timings

        events = utils.ordered_events()
        if 'event' in context:
            events = events.exclude(id = context['event'].id)
        context['recent_events'] = events[:3]

        return context


    @staticmethod
    def augment_events_for_events_boxes(
        events: Iterable['AugmentedEvent'],
        user: auth.User | auth.AnonymousUser,
    ) -> None:
        """Prefetches data and sets additional event attributes for use with an event box."""

        # Add default financial and days prefetch
        seats = models.Seat.objects.all()
        db.prefetch_related_objects(events, db.Prefetch('days', to_attr = '_days'))

        # Additional augmentation for logged in users
        if not user.is_anonymous:

            # User financial data prefetch
            db.prefetch_related_objects(
                events,
                db.Prefetch(
                    'fantasies',
                    queryset = (
                        models.GameEntry.objects
                        .filter(team = user.team)
                        .extend_financials()
                    ),
                    to_attr = '_user_fantasy',
                ),
            )

            # User crews prefetch
            active_days = [event.active_day for event in events]
            db.prefetch_related_objects(
                active_days,
                db.Prefetch(
                    'purchases',
                    queryset = (
                        models.Purchase.objects
                        .filter(crew__gender = Genders.MEN, team = user.team)
                    ),
                    to_attr = 'mens_crew',
                ),
                db.Prefetch(
                    'purchases',
                    queryset = (
                        models.Purchase.objects
                        .filter(crew__gender = Genders.WOMEN, team = user.team)
                    ),
                    to_attr = 'womens_crew',
                ),
            )

            # Add user-specific extra event information
            for event in events:
                if event._user_fantasy:
                    event.user_fantasy = event._user_fantasy[0]
                event.mens_crew_ready = utils.has_all_seats(event.active_day.mens_crew, seats)
                event.womens_crew_ready = utils.has_all_seats(event.active_day.womens_crew, seats)



class IndexView(FantasyBaseMixin, TemplateView):
    template_name = 'fantasy/index.html'

    def get_context_data(self, **kwargs: ContextKwargs) -> ContextDict:
        context = super().get_context_data(**kwargs)

        # Load and augment events
        context['recent_events'] = list(context['recent_events'])
        self.augment_events_for_events_boxes(context['recent_events'], self.request.user)

        return context



class RulesView(FantasyBaseMixin, TemplateView):
    template_name = 'fantasy/rules.html'



class EventsList(FantasyBaseMixin, TemplateView):
    template_name = 'fantasy/events.html'

    def get_context_data(self, **kwargs: ContextKwargs) -> ContextDict:
        context = super().get_context_data(**kwargs)

        # Load and augment events
        context['recent_events'] = list(context['recent_events'])
        context['past_events'] = list(utils.ordered_events().exclude(
            id__in = [event.id for event in context['recent_events']],
        ))

        self.augment_events_for_events_boxes(
            context['past_events'] + context['recent_events'],
            self.request.user,
        )

        return context



class EventBase(FantasyBaseMixin, EventDetailView):
    """A base view for event-specific pages."""

    # View settings
    model = models.Event
    slug_url_kwarg = 'event_tag'
    slug_field = 'tag'

    def get_context_data(self, **kwargs: ContextKwargs) -> ContextDict:
        context = super().get_context_data(**kwargs)

        self.event = self.object  # Provide friendly name for retrived event.
        self.day = self.event.active_day
        context['day'] = self.day

        if self.request.user.is_authenticated:
            self.team = self.request.user.team
            context['team'] = self.team

        return context



class EventView(EventBase):
    """An main page for an event."""

    # View settings
    template_name = 'fantasy/event.html'

    def popular_crew_query(self, gender: Genders) -> db.QuerySet[CrewWithPopularity]:
        """Creates a Crew queryset with purchase counts and popularity scores."""

        purchase_count = db.Count(
            'purchases',
            filter = db.Q(purchases__day = self.day),
        )
        popularity = db.ExpressionWrapper(
            db.F('purchase_count') / self.game_entry_count,
            db.FloatField(),
        )

        return (
            models.Crew.objects
            .filter(gender = gender, positions__day = self.day)
            .annotate(purchase_count = purchase_count)
            .annotate(popularity = popularity)
            .order_by('-purchase_count', 'positions__rank')
            # ^ Sort by popularity not possible on SQLite
        )[:5]


    def get_context_data(self, **kwargs: ContextKwargs) -> ContextDict:
        context = super().get_context_data(**kwargs)

        # Leaderboard data
        context['fantasies'] = (
            self.event.fantasies
            .select_related('team', 'team__user')
            .extend_financials()
            .rank_by(GENDERS_OVERALL)
        )[:5]

        # Crew popularity data
        self.game_entry_count = self.event.fantasies.count() or 1  # Avoid Div0 error
        context['popular_crews_men'] = self.popular_crew_query(Genders.MEN)
        context['popular_crews_women'] = self.popular_crew_query(Genders.WOMEN)

        return context



class MarketView(EventBase):
    """Presents the market pages for an event."""

    # View settings
    template_name = 'fantasy/market.html'

    def add_purchase_count(
        self,
        start_order: db.QuerySet[models.Position],
    ) -> db.QuerySet[PositionWithPopularity]:
        """Extends a purchase queryset with purchase counts and popularity scores."""

        purchase_count = db.Count(
            'crew__purchases',
            filter = db.Q(crew__purchases__day = self.day),
        )
        popularity = db.ExpressionWrapper(
            db.F('purchase_count') / self.game_entry_count,
            db.FloatField(),
        )
        return (
            start_order
            .annotate(purchase_count = purchase_count)
            .annotate(popularity = popularity)
        )


    def get_context_data(self, **kwargs: ContextKwargs) -> ContextDict:
        context = super().get_context_data(**kwargs)

        gender = self.kwargs['gender']
        context['gender'] = gender
        seats = models.Seat.objects.all()
        context['seats'] = seats

        self.game_entry_count = self.day.event.fantasies.count() or 1  # Avoid Div0 error
        context['start_order'] = [
            self.add_purchase_count(division_start_order)
            for division_start_order in self.day.start_order(gender)
        ]

        user = self.request.user
        if user.is_authenticated:

            context['crew'] = (
                user.team
                .get_crew(self.day, gender)
                .select_related('seat', 'crew', 'athlete')
                .prefetch_related(db.Prefetch(
                    'crew__positions',
                    models.Position.objects.filter(day = self.day),
                    to_attr = '_position',
                ))
            )
            for purchase in context['crew']:
                purchase.price = utils.pricing_by_day_gender(
                    purchase.crew._position[0].rank,
                    self.day,
                    gender,
                )
            context['crew_valid'] = utils.has_all_seats(context['crew'], seats)

            other_gender = utils.reverse_gender(gender)
            other_crew = user.team.get_crew(self.day, other_gender)
            context['other_crew_valid'] = utils.has_all_seats(other_crew, seats)

fantasy/templates/fantasy/event-box.html
{% load fantasy_tags %}
  <div class="card mb-3">
    <div class="card-header text-dark d-flex justify-content-between">
      <h4 class="mb-0">
        {{ event }}{% if user.is_superuser %}
        &nbsp;
        {% include 'fantasy/market-held-closed-toggle.html' %}{% endif %}
      </h4>
      <a href="{% url 'fantasy:event' event.tag %}" class="btn btn-primary btn-sm" style="width: 2.2em">
        <small><span class="oi oi-chevron-right"></span></small>
      </a>
    </div>
    <div class="card-body pb-0">
      <div class="row">
        <div class="col-xl-3 mb-3 alert">
          {{ event.first_day.date|date:"l" }}&nbsp;{{ event.first_day.date|date:"M" }}&nbsp;{{ event.first_day.date|date:"jS" }}
          - {{ event.last_racing_day.date|date:"l" }}&nbsp;{{ event.last_racing_day.date|date:"M" }}&nbsp;{{ event.last_racing_day.date|date:"jS" }}
        </div>
        <div class="col-xl-6">
          <table class="table table-sm table-borderless">
            <tr>
              <th class="align-middle text-center">Men's crew</th>
              <td class="align-middle">
                {{ event.user_fantasy.mens_budget|default:money.INITIAL_BALANCE|currency }}
                 / {{ event.user_fantasy.mens_crew_value|default:0|currency }}
              </td>
              <td class="align-middle" style="width: 35%">
                {% crew_ready_button event genders.MEN %}
              </td>
            <tr>
            <tr>
              <th class="align-middle text-center">Women's crew</th>
              <td class="align-middle">
                {{ event.user_fantasy.womens_budget|default:money.INITIAL_BALANCE|currency }}
                 / {{ event.user_fantasy.womens_crew_value|default:0|currency }}
              </td>
              <td class="align-middle" style="width: 20%">
                {% crew_ready_button event genders.WOMEN %}
              </td>
            <tr>
          </table>
        </div>
        <div class="col-xl-3 text-center">
          {% market_status_box event.active_day False %}
        </div>
      </div>
    </div>
  </div>

fantasy/templates/fantasy/event.html
{% extends 'core/base.html' %}
{% load fantasy_tags %}
{% load static %}

{% block page_head %}
<link rel="stylesheet" type="text/css" href="{% static 'fantasy/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'fantasy/club_styles.css' %}">
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md mb-3">
      <h1>{{ event }}</h1>
      <div class="mb-3">
        {{ event.first_day.date|date:"l F jS" }} - {{ event.last_racing_day.date|date:"l F jS" }}
      </div>
      <div class="card card-body bg-light text-dark">
        <a href="https://bumps.live/" target="_blank" class="text-reset text-decoration-none">
          <div class="d-flex justify-content-between">
          <div>
            <image src="https://bumps.live/blades.png" style="height: 3.5em">
          </div>
          <div>
            <span>In collaboration with</span>
            <h3 class="mb-0">Live Bumps</h3>
          </div>
          <div>
            <image src="https://bumps.live/spoons.png" style="height: 3.5em">
          </div>
        </div></a>
      </div>
    </div>
    <div class="col-md mb-3">
      <div class="list-group">
        <div class="list-group-item list-group-item-primary">
          <div class="row justify-content-between">
            <span class="ml-3">Leaderboard</span>
            <a
              href="{% url 'fantasy:leaderboard' event.tag %}"
              class="btn btn-primary btn-sm"
              style="padding-top: 0.1em; padding-bottom: 0.1em; margin: 0"
            >
              See all
            </a>
          </div>
        </div>
        {% for fantasy in fantasies %}
        {% mini_leaderboard_row forloop.counter fantasy event %}{% endfor %}
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md mb-3">
      <div class="list-group">
        <div class="list-group-item list-group-item-primary">Most Popular Men's Crews</div>
        {% for crew in popular_crews_men %}
        {% popularity_row forloop.counter crew %}{% endfor %}
      </div>
    </div>
    <div class="col-md mb-3">
      <div class="list-group">
        <div class="list-group-item list-group-item-primary">Most Popular Women's Crews</div>
        {% for crew in popular_crews_women %}
        {% popularity_row forloop.counter crew %}{% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

fantasy/templates/fantasy/events.html
{% extends 'core/base.html' %}
{% load fantasy_tags %}

{% block content %}

<h3 class="mb-3">Latest events</h3>
{% for event in recent_events %}
{% event_box event user %}
{% empty %}
There are no events available
{% endfor %}

{% if past_events %}
<h3 class="mb-3">Past events</h3>
{% for event in past_events %}
{% event_box event user %}
{% endfor %}
{% endif %}

{% endblock%}

fantasy/templates/fantasy/form.html
{% extends 'core/base.html' %}
{% load fantasy_tags %}

{% block content %}

<form method="post">
  {% csrf_token %}
  <table class="table table-borderless">
  {% for field in form %}
  <tr>
    <th class="text-right">{{ field.label }}</th>
    <td>{{ field }}</td>
    <td>{{ field.errors }}</td>
  </tr>
  {% endfor %}
    <tfoot><tr>
      <td></td>
      <td><input type="submit" value="Buy"></td>
      <td></td>
    </tr></tfoot>
  </table>
</form>

{% endblock%}

fantasy/templates/fantasy/index.html
{% extends 'core/base.html' %}
{% load fantasy_tags %}

{% block content %}

{% for event in recent_events %}
{% event_box event user %}
{% empty %}
There are no events available
{% endfor %}
{% endblock%}

fantasy/templates/fantasy/leaderboard.html
{% extends 'core/base.html' %}
{% load fantasy_tags %}

{% block page_head %}
<style type="text/css">
  .table>thead>tr>th {
    vertical-align: top;
    border-top: 0;
    padding-left: 0.5em;
    padding-right: 0.5em;
  }
  .narrow-column {
    width: 10em;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }
</style>

<script type="text/javascript">
  $(document).ready(function () {
    $('[data-toggle="tooltip"]').tooltip();
  });
</script>
{% endblock %}

{% block content %}
<div class="row"><div class="col">
  <h3>{% if ranking == GENDERS_OVERALL %}Overall{% elif ranking == genders.MEN %}Men's{% else %}Women's{% endif %} ranking</h3>
  <div class="mb-3">
    {% if ranking == GENDERS_OVERALL %}Teams are ranked by the total number of crabs accumulated and then by the combined value of their crews.
    {% else %}Teams are ranked by the number of crabs their {{ ranking.label|lower }}'s crew has accumulated and then by the value of their {{ ranking.label|lower }}'s crews.{% endif %}
  </div>

  <div class="card mb-3">
    <table class="table table-hover table-sm table-responsive-md text-center mb-0 mt-0">
      <thead class="thead-light"><tr>
        <th>Rank</th>
        <th class="text-left">Team</th>
        <th>
          <span>Overall</span>
          <a href="{% url 'fantasy:leaderboard' event.tag %}" class="btn btn-{% if ranking == GENDERS_OVERALL %}success{% else %}primary{% endif %} btn-sm px-1 py-0 ml-1">
            <small><span class="oi oi-sort-descending"></span></small>
          </a>
        </th>
        <th>
          <span>Men</span>
          <a href="{% url 'fantasy:leaderboard_men' event.tag %}" class="btn btn-{% if ranking == genders.MEN %}success{% else %}primary{% endif %} btn-sm px-1 py-0 ml-1">
            <small><span class="oi oi-sort-descending"></span></small>
          </a>
        </th>
        <th>
          <span>Women</span>
          <a href="{% url 'fantasy:leaderboard_women' event.tag %}" class="btn btn-{% if ranking == genders.WOMEN %}success{% else %}primary{% endif %} btn-sm px-1 py-0 ml-1">
            <small><span class="oi oi-sort-descending"></span></small>
          </a>
        </th>
        <th>Crews</th>
      </tr></thead>
      <tbody>
        {% for fantasy in fantasies %}<tr {% if fantasy.team == team %}class="table-info"{% endif %}>
          <td>{{ forloop.counter }}</td>
          <td class="text-left">
            <div class="team-name d-none d-md-block">{{ fantasy.team }}</div>
            <div class="narrow-column d-block d-md-none" data-toggle="tooltip" data-placement="bottom" title="{{ fantasy.team }}">{{ fantasy.team }}</div>
          </td>
          <td>
            <span>{{ fantasy.total_budget }}</span>
            <small>{{ fantasy.total_crew_value }}</small>
          </td>
          <td>
            <span>{{ fantasy.mens_budget }}</span>
            <small>{{ fantasy.mens_crew_value }}</small>
          </td>
          <td>
            <span>{{ fantasy.womens_budget }}</span>
            <small>{{ fantasy.womens_crew_value }}</small>
          </td>
          <td class="align-middle">
            <a href="{% url 'fantasy:team' event.tag fantasy.team.user.username %}" class="btn btn-secondary btn-sm pt-0 pl-2 pr-2" style="padding-bottom: 2px">
              <small><span class="oi oi-chevron-right"></span></small>
            </a>
          </td>
        </tr>{% endfor %}
      </tbody>
    </table>
  </div>
</div></div>

{% endblock %}

fantasy/templates/fantasy/market-held-closed-toggle.html
<form id="buy-form" action="{% url 'fantasy:market-hold' %}" method="post" style="display: inline">
          {% csrf_token %}
          <input id="event" name="event" type="hidden" value="{{ event.tag }}" />
          <input id="toggle-from" name="toggle-from" type="hidden" value="{{ event.market_held_closed }}" />
          <input type="submit" class="btn btn-danger btn-sm" value="{% if event.market_held_closed %}Re-open{% else %}Close{% endif %}" />
        </form>

fantasy/templates/fantasy/market.html
{% extends 'core/base.html' %}
{% load fantasy_tags %}
{% load static %}

{% block page_head %}
<link rel="stylesheet" type="text/css" href="{% static 'fantasy/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'fantasy/club_styles.css' %}">
<style type="text/css">
  .popover .popover-body {
    padding: 0em;
  }
</style>

<script type="text/javascript">
  $(document).ready(function () {
    $(".btn-sell").click(sell);
    $(".btn-buy:not(.disabled)").click(buy);
    $('[data-toggle="tooltip"]').tooltip({delay: {"show": 750, "hide": 0}});
    $('[data-toggle="popover"]').popover({
      html: true,
      trigger: 'focus',
      content: function() {
        $('#analysis-popularity').html($(this).data('popularity'));

        $('#analysis-bump-up').html($(this).data('bump-up'));
        $('#analysis-row-over').html($(this).data('row-over'));
        $('#analysis-bumped-down').html($(this).data('bumped-down'));

        if ($(this).data('bump-up') === '+0') {
          $('#analysis-bump-up-row').hide();
          $('#analysis-row-over-row').addClass('analysis-top-row');
          $('#analysis-row-over-row').find('.badge').addClass('badge-success').removeClass('badge-warning');
        } else {
          $('#analysis-bump-up-row').show();
          $('#analysis-row-over-row').removeClass('analysis-top-row');
          $('#analysis-row-over-row').find('.badge').removeClass(['badge-success', 'badge-danger']).addClass('badge-warning');
        }
        if ($(this).data('bumped-down') === '+0') {
          $('#analysis-bumped-down-row').hide();
          $('#analysis-row-over-row').find('.badge').addClass('badge-danger').removeClass('badge-warning');
        } else {
          $('#analysis-bumped-down-row').show();
        }

        return $('#analysis_wrapper').html();
      }
    });
  });

  function buy(event) {
    $("#buy-day").val($(event.target).data('day'));
    $("#buy-crew").val($(event.target).data('crew'));
    if ($("#buy-day").val() && $("#buy-crew").val()) {
      $("#buy-form").submit();
    };
  };

  function sell(event){
    $("#sell-purchase").val($(event.target).data('purchase'));
    if ($("#sell-purchase").val()) {
      $("#sell-form").submit();
    };
  };
</script>
{% endblock %}


{% block content %}
<div class="row"><div class="col">
  {% market_status_box day %}
</div></div>

<div class="row">
  {% if user.is_authenticated %}<div class="col-lg-5 order-lg-last">
    <div class="list-group sticky-top mb-3" style="z-index: 980">
      {% crew_list_box crew seats finances show_actions %}
      {% crew_status_box event gender crew_valid other_crew_valid %}
    </div>
    <br/>
  </div>{% endif %}
  
  <div class="col-lg order-lg-first">
    {% for division in start_order %}
      {% market_division_box division gender forloop.counter finances.balance|default:0 show_actions %}
    {% endfor %}
  </div>
</div>

<form id="buy-form" action="{% url 'fantasy:buy' %}" method="post">
  {% csrf_token %}
  <input id="buy-day" name="day" type="hidden" value=""/>
  <input id="buy-crew" name="crew" type="hidden" value=""/>
</form>

<form id="sell-form" action="{% url 'fantasy:sell' %}" method="post">
  {% csrf_token %}
  <input id="sell-event" name="event" type="hidden" value="{{ event.tag }}">
  <input id="sell-gender" name="gender" type="hidden" value="{{ gender }}">
  <input id="sell-purchase" name="purchase" type="hidden" value=""/>
</form>

<div id="analysis_wrapper" style="display: none">
  <table class="table table-sm text-center analysis-box">
    <tr class="analysis-top-row" id="analysis-bump-up-row">
      <td><span class="badge badge-success">+1</span></td>
      <td><span id="analysis-bump-up">-</span>{{ ''|currency }}</td>
    </tr>
    <tr id="analysis-row-over-row">
      <td><span class="badge badge-warning"><span class="oi oi-arrow-right"></span></span></td>
      <td><span id="analysis-row-over">-</span>{{ ''|currency }}</td>
    </tr>
    <tr id="analysis-bumped-down-row">
      <td><span class="badge badge-danger">&minus;1</span></td>
      <td><span id="analysis-bumped-down">-</span>{{ ''|currency }}</td>
    </tr>
    <tr>
      <td>Popularity</td>
      <td><span id="analysis-popularity">-</span></td>
    </tr>
  </table>
</div>

{% endblock%}

fantasy/templates/fantasy/switch.html
{% extends 'core/base.html' %}
{% load fantasy_tags %}
{% load static %}


{% block content %}

<div class="container text-center" style="max-width: 30em; margin-top: 1.5em">

<h3>Micromanage crew</h3>
Alter puchase of {% if purchase.athlete %}<strong>{{ purchase.athlete }}</strong> ({{ purchase.crew }}){% else %}{{ purchase.crew }}{% endif %}

<form action="{% url 'fantasy:switch' purchase.id %}" method="post">
  {% csrf_token %}

  <div class="row">

  <div class="col-sm" style="margin-top: 1em">
    <strong>Pick your athlete</strong><br/>
    <div class="btn-group-vertical btn-group-toggle" data-toggle="buttons" style="margin-top: 0.5em">
      {% for rower in rowers %}
        <label class="btn {% if rower not in other_purchased_athletes and not rower.seat.cox %}btn-outline-primary{% else %}btn-outline-secondary disabled{% endif %}{% if rower == purchase.athlete %} active{% endif %}">
          {% if rower not in other_purchased_athletes and not rower.seat.cox %}
            <input type="radio" name="athlete" value="{{ rower.id }}" {% if rower == purchase.athlete %}checked{% endif %} />
          {% endif %}
            {{ rower }}
        </label>
      {% endfor %}
        <label class="btn btn-outline-primary{% if not purchase.athlete %} active{% endif %}">
          <input type="radio" name="athlete" value="0"{% if not purchase.athlete %} checked{% endif %} /><strong>Anonymous athlete</strong>
        </label>
    </div>
  </div>
  
  
  <div class="col-sm" style="margin-top: 1em">
    <strong>Pick their seat</strong><br/>
    <div class="btn-group-vertical btn-group-toggle" data-toggle="buttons" style="margin-top: 0.5em">
      {% for seat in seats %}
        <label class="btn {% if not seat.cox %}btn-outline-primary{% else %}btn-outline-secondary disabled{% endif %}{% if seat == purchase.seat %} active{% endif %}">
          {% if not seat.cox %}
            <input type="radio" name="seat" value="{{ seat.id }}"{% if seat == purchase.seat %} checked{% endif %} />
          {% endif %}
            {{ seat }}
      </label>
      {% endfor %}
    </div>
  </div>
  
  </div>
  
  <div class="row" style="margin-top: 1.5em">
    <div class="col">
      <input class="btn btn-primary" type="submit" value="Make Change" />
    </div>
  </div>
  
  
</form>

</div>
{% endblock %}