core/urls.py
import os

from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import TemplateView

from . import settings
from . import views


urlpatterns = [
    path('accounts/signup/', views.UserCreationView.as_view(), name = 'signup'),
    path('accounts/profile/', views.UserProfileView.as_view(), name = 'profile'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('robots.txt', TemplateView.as_view(template_name = 'core/robots.txt')),
    path('', include('fantasy.urls')),
    path('', lambda req: None, name = 'index'),  # type: ignore # Root URL alias, handled by app
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        'favicon.ico',
        document_root = os.path.join(settings.BASE_DIR, 'core', 'static', 'favicon.ico'),
    )

fantasy/urls.py
from django.urls import path, include

from .constants import Genders
from . import views


app_name = 'fantasy'

leaderboard_subpatterns = [
    path(
        'men/',
        views.LeaderboardView.as_view(),
        {'gender': Genders.MEN},
        name = 'leaderboard_men',
    ),
    path(
        'women/',
        views.LeaderboardView.as_view(),
        {'gender': Genders.WOMEN},
        name = 'leaderboard_women',
    ),
    path(
        '',
        views.LeaderboardView.as_view(),
        name = 'leaderboard',
    ),
]

urlpatterns = [
    path('events/', views.EventsList.as_view(), name = 'events'),
    path('guide-rules/', views.RulesView.as_view(), name = 'rules'),
    path(
        'privacy/',
        views.RulesView.as_view(template_name = 'fantasy/privacy.html'),
        name = 'privacy',
    ),
    path('buy/', views.buy, name = 'buy'),
    path('sell/', views.sell, name = 'sell'),
    path('switch/<int:purchase_id>/', views.Switch.as_view(), name = 'switch'),
    path('market-hold/', views.market_hold, name = 'market-hold'),
    path('<slug:event_tag>/', include([
        path('men/', views.MarketView.as_view(), {'gender': Genders.MEN}, name = 'men'),
        path('women/', views.MarketView.as_view(), {'gender': Genders.WOMEN}, name = 'women'),
        path('leaderboard/', include(leaderboard_subpatterns)),
        path('teams/<team_name>/', views.TeamView.as_view(), name = 'team'),
        path(
            'guide-rules/',
            views.EventBase.as_view(template_name = 'fantasy/rules.html'),
            name = 'rules',
        ),
        path(
            'privacy/',
            views.EventBase.as_view(template_name = 'fantasy/privacy.html'),
            name = 'privacy',
        ),
        path('', views.EventView.as_view(), name = 'event'),
    ])),
    path('', views.IndexView.as_view(), name = 'index'),
]

core/forms.py
import re
from typing import TYPE_CHECKING

from django import forms
from django.contrib.auth import models as auth
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError


if TYPE_CHECKING:
    ProfileCreateFormBase = UserCreationForm[auth.User]
    ProfileEditFormBase = forms.ModelForm[auth.User]
else:
    ProfileCreateFormBase = UserCreationForm
    ProfileEditFormBase = forms.ModelForm


username_blacklist_regexes: list[tuple[str, str]] = [
    ('blacklisttest', ''),
    ('hitchen', 'The admin requests that you do not feature them in your team name.'),
    (
        'hitchin',
        'The admin requests that you do not feature them in your team name.'
        + ' Also you spelt it wrong.',
    ),
    ('quarrell', 'This team name is not allowed to prevent violations of rule F0.'),
    ('rq', 'This team name is not allowed to prevent violations of rule F0.'),
]


class UserCreationWithEmailForm(ProfileCreateFormBase):
    email = forms.EmailField(required = False)

    def clean_username(self) -> str:
        username = self.cleaned_data['username']

        if not isinstance(username, str):
            raise ValidationError('Username must be a string')

        if not re.match('^[a-z0-9]+$', username, re.IGNORECASE):
            raise ValidationError('Usernames can only contain letters and numbers.')

        if auth.User.objects.filter(username__icontains = username).exists():
            raise ValidationError('This team name is already taken.')

        for blacklist, error_message in username_blacklist_regexes:
            if re.search(blacklist, username, re.IGNORECASE):
                raise ValidationError(error_message or 'This team name is not permitted.')

        return username


    def save(self, commit: bool = False) -> auth.User:
        """Adds an optional e-mail address to the new user."""

        user = super().save(commit = commit)
        if 'email' in self.cleaned_data:
            user.email = self.cleaned_data['email']

        user.save()
        return user



class UserProfileForm(ProfileEditFormBase):
    """A user-update form with an optional e-mail field."""

    class Meta:
        model = auth.User
        fields = ('email',)

core/views.py
from typing import Any, TYPE_CHECKING

from django.views.generic.edit import CreateView, UpdateView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth import authenticate, login, models as auth
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import models as db
from django.urls import reverse_lazy

from . import forms


if TYPE_CHECKING:
    from django.http import HttpResponse
    from django.forms.forms import BaseForm

    ProfileCreateView = CreateView[auth.User, forms.UserCreationWithEmailForm]
    ProfileUpdateView = UpdateView[auth.User, forms.UserProfileForm]
    ProfileQuerySet = db.QuerySet[auth.User]
    FormSuccessMessageMixin = SuccessMessageMixin[BaseForm]
else:
    ProfileCreateView = CreateView
    ProfileUpdateView = UpdateView
    ProfileQuerySet = db.QuerySet
    FormSuccessMessageMixin = SuccessMessageMixin


class UserCreationView(FormSuccessMessageMixin, ProfileCreateView):
    """Renders and processes a user creation form."""

    # View settings
    form_class = forms.UserCreationWithEmailForm
    template_name = 'registration/signup.html'
    success_url = reverse_lazy('index')

    def get_success_message(self, cleaned_data: dict[str, str]) -> str:
        return 'Welcome {} - Your account has been created.'.format(self.object)

    def form_valid(self, form: 'BaseForm') -> 'HttpResponse':
        """Creates and signs in the new user."""

        redirect = super().form_valid(form)
        authed_user = authenticate(
            username = form.cleaned_data['username'],
            password = form.cleaned_data['password1'],
        )
        login(self.request, authed_user)
        return redirect



class UserProfileView(LoginRequiredMixin, FormSuccessMessageMixin, ProfileUpdateView):
    """Renders and processes a user update form."""

    # View settings
    form_class = forms.UserProfileForm
    template_name = 'registration/profile.html'
    redirect_field_name = None
    success_url = reverse_lazy('profile')
    success_message = 'Profile updated'

    def get_object(self, queryset: ProfileQuerySet | None = None) -> Any:
        return self.request.user

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>Fantasy Bumps</title>

<!-- Bootstrap -->
<link rel="stylesheet" href="{% static 'core/bootstrap.min.css' %}" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css" integrity="sha256-BJ/G+e+y7bQdrYkS2RBTyNfBHpA9IuGaPmf9htub5MQ=" crossorigin="anonymous" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Bootstrap -->

<link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}" >

{% block page_head %}{% endblock %}

</head>

<body>

{% include 'core/nav.html' %}

<div class="container">
<div class="row"><div class="col mb-3"><!-- Page-top spacing --></div></div>
{% include 'core/messages.html' %}
{% block content %}
{% endblock %}
</div>

</body>
</html>

core/templates/core/messages.html
{% for message in messages %}
<div class="alert alert-{{message.tags}} alert-dismissible" role="alert">
  {{ message }}
  <button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
</div>
{% endfor %}

core/templates/core/nav-events-dropdown.html
<div class="nav-item dropdown {% if link_text %}d-block d-lg-none{% else %}d-none d-lg-block{% endif %}">
        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown"{% if not link_text %} style="margin-left: -0.75em"{% endif %}>{{ link_text }}</a>
        <div class="dropdown-menu">{% for recent_event in recent_events %}
          <a class="dropdown-item" href="{% url 'fantasy:event' recent_event.tag %}">{{ recent_event }}</a>{% endfor %}
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'fantasy:events' %}">All events</a>
        </div>
      </div>

core/templates/core/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  
  <a class="navbar-brand" href="{% url 'fantasy:index' %}">Fantasy Bumps</a>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar_menu">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <div class="collapse navbar-collapse" id="navbar_menu">
    <div class="navbar-nav">
      {% if event %}
      <a class="nav-item navbar-brand" href="{% url 'fantasy:event' event.tag %}">{{ event }}</a>
      {% endif %}
      {% include 'core/nav-events-dropdown.html' %}
      {% if event %}
      <a class="nav-item nav-link" href="{% url 'fantasy:men' event.tag %}">Men</a>
      <a class="nav-item nav-link" href="{% url 'fantasy:women' event.tag %}">Women</a>
      <a class="nav-item nav-link" href="{% url 'fantasy:leaderboard' event.tag %}">Leaderboard</a>
      {% include 'core/nav-events-dropdown.html' with link_text='Other Events' %}
      <div class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">Information</a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'fantasy:rules' event.tag %}">Guide & Rules</a>
          <a class="dropdown-item" href="{% url 'fantasy:privacy' event.tag %}">Privacy Policy</a>
        </div>
      </div>
      {% else %}
      {% include 'core/nav-events-dropdown.html'  with link_text='Events' %}
      <div class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">Information</a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'fantasy:rules' %}">Guide & Rules</a>
          <a class="dropdown-item" href="{% url 'fantasy:privacy' %}">Privacy Policy</a>
        </div>
      </div>
      {% endif %}
    </div>
  </div>
  
  <div class="collapse navbar-collapse justify-content-end" id="navbar_menu">
    <div class="navbar-nav">
      {% if user.is_authenticated %}
      <div class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
          {{ user.username }}
        </a>
        <div class="dropdown-menu dropdown-menu-right">
          {% if event %}<a class="dropdown-item" href="{% url 'fantasy:team' event.tag user.username %}">My Crews</a>{% endif %}
          <a class="dropdown-item" href="{% url 'profile'%}">My Account</a>
          <div class="dropdown-divider"></div>
          <form method="post" action="{% url 'logout' %}">
            {% csrf_token %}
            <button type="submit" class="dropdown-item">Sign out</button>
          </form>
        </div>
      </div>
      {% else %}
      <a class="nav-item nav-link" href="{% url 'login' %}"><button class="btn btn-outline-light btn-sm" type="button">Sign in</button></a>
      {% endif %}
    </div>
  </div>
  
</nav>